default_platform(:android)

platform :android do
  desc "Build a debug APK"
  lane :build_and_distribute do
    sh("flutter build apk --debug --build-number=#{ENV['BUILD_NUMBER']}")
    apk_path = "build/app/outputs/flutter-apk/app-debug.apk"
    #preparing and uploading
    
    firebase_app_distribution(
      app: ENV["FIREBASE_APP_ID"],
      android_artifact_path: apk_path,
      android_artifact_type: "APK",
      testers: ENV["FIREBASE_TESTERS"],
      service_credentials_json_data: ENV["FIREBASE_SERVICE_ACCOUNT_JSON"]
    )

    UI.success("✅ Build completed and distributed to Firebase!")

  end
end

